name: Debug Token Generation

on:
  workflow_dispatch:

jobs:
  debug-token:
    name: Debug GitHub App Token
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets Exist
        run: |
          echo "APP_ID exists: ${{ secrets.APP_ID != '' }}"
          echo "PEMCONTENTS exists: ${{ secrets.PEMCONTENTS != '' }}"
          # Show the first few characters of PEMCONTENTS to verify format
          echo "PEMCONTENTS preview: ${{ secrets.PEMCONTENTS != '' && format('{0}...', secrets.PEMCONTENTS[:30]) }}"
          
      - name: Try Token Generation
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PEMCONTENTS }}
          repository: Ali-Moatazz/gold-

      - name: Success Message
        if: success()
        run: echo "✅ Token generated successfully!"
        
      - name: Show Token Info
        if: success()
        run: |
          echo "Token was generated successfully"
          # The token itself will be masked for security
