name: My Workflow

on:
  workflow_dispatch:

jobs:
  generate-token:
    name: Generate GitHub App token
    runs-on: ubuntu-latest
    outputs: 
      app_token: ${{ steps.app-token.outputs.token }}
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PEMCONTENTS }}
          repository: Ali-Moatazz/gold-   # ✅ needed for API-scoped token

  update-gold-via-api:
    name: Update gold repo via GitHub API
    runs-on: ubuntu-latest
    needs: generate-token
    steps:
      - name: Create hello.txt in gold repo
        uses: devops-infra/action-github-file@v2   # ✅ replaced checkout with API action
        with:
          github_token: ${{ needs.generate-token.outputs.app_token }}  # ✅ GitHub App token
          repository: Ali-Moatazz/gold-
          file: hello.txt
          branch: my-branch
          content: "Hello Ali"
          commit_message: "Add hello.txt"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ needs.generate-token.outputs.app_token }}
          repository: Ali-Moatazz/gold-   # ✅ must specify repo for App token usage
          branch: my-branch
          base: main
          title: "Add hello.txt"
          body: "This PR adds hello.txt with greeting message."
          
      - name: Merge Pull Request
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ needs.generate-token.outputs.app_token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
