name: Sync to Gold Repo

on:
  workflow_dispatch:

jobs:
  sync-gold:
    name: Sync and PR to Gold Repo
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PEMCONTENTS }}
          owner: ${{ github.repository_owner }}

      - name: Checkout gold- repo
        uses: actions/checkout@v4
        with:
          repository: Ali-Moatazz/gold
          token: ${{ steps.generate-token.outputs.token }}
          path: gold
          
      - name: whereami
        run: |
          cd gold
          pwd
          ls  
          
      - name: Create hello.txt
        run: |
          cd gold
          touch hello.txt
          echo "Hello Ali" > hello.txt
          cat hello.txt
          ls
          
      - name: Configure Git credentials
        run: |
          echo "https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com" > ~/.git-credentials
          git config --global credential.helper store
          git config --global user.name "mynameisaly[bot]"
          git config --global user.email "mynameisaly[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          cd gold
          git checkout -b aly
          git add hello.txt
          git commit -m "Add hello.txt"
          ls
          
      - name: Push changes to new branch
        env:
          GH_APP_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          cd gold
          git push https://x-access-token:${GH_APP_TOKEN}@github.com/Ali-Moatazz/gold.git aly
          
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ steps.generate-token.outputs.token }}" | gh auth login --with-token
          
      - name: Create Pull Request manually
        run: |
          cd gold
          gh pr create \
            --base main \
            --head aly \
            --title "Add hello.txt" \
            --body "This PR adds hello.txt with greeting message."
            
      - name: Enable auto-merge
        run: gh pr merge --auto --delete-branch --squash "$PR_NUMBER" # Replace $PR_NUMBER with the actual PR number or a variable
        env:
            GH_APP_TOKEN: ${{ steps.generate-token.outputs.token }}
