name: My Workflow

on:
  workflow_dispatch:

jobs:
  generate-token:
    name: Generate GitHub App token
    runs-on: ubuntu-latest
    env:
       APP_ID: ${{ secrets.APP_ID }} 
      
    outputs: 
      app-token: ${{ steps.generate.outputs.token }}   # ✅ correct reference
    steps:
      - id: generate   # ✅ step id = generate
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PEMCONTENTS }}

      - name: print app id
        run: |
          echo -n "$APP_ID" | xxd -ps
         
  checkout-to-gold:
    name: Checkout to gold repo
    runs-on: ubuntu-latest
    needs: generate-token
      
    steps:
      - name: print variable
        run: |
          echo "Using token: ${{ needs.generate-token.outputs.app-token }}"

      - id: checkout
        uses: actions/checkout@v4
        with:
          repository: Ali-Moatazz/gold-   # ✅ make sure repo name is correct
          token: ${{ needs.generate-token.outputs.app-token }}   # ✅ this will now be set
          path: gold

      - name: Create hello.txt
        run: echo "Hello Ali" > hello.txt
        working-directory: gold

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add hello.txt
          git commit -m "Add hello.txt" || echo "No changes to commit"
        working-directory: gold

      - name: Push changes to new branch
        run: git push origin HEAD:my-branch
        working-directory: gold
        env: 
          GITHUB_TOKEN: ${{ needs.generate-token.outputs.app-token }}
        
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ needs.generate-token.outputs.app-token }}
          path: gold
          branch: my-branch
          base: main
          title: "Add hello.txt"
          body: "This PR adds hello.txt with greeting message."
          
      - name: Merge Pull Request
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ needs.generate-token.outputs.app-token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
