name: Auto PR to gold repo

on:
  workflow_dispatch:

jobs:
  generate-token:
    name: Generate GitHub App token
    runs-on: ubuntu-latest
    outputs:
      app_token: ${{ steps.generate.outputs.token }}
    steps:
      - name: Generate token
        id: generate
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.app-id }}
          private-key: ${{ secrets.PEMCONTENTS }}

  create-pr:
    name: Create & Merge PR in gold repo
    runs-on: ubuntu-latest
    needs: generate-token
    steps:
      - name: Checkout gold repo
        uses: actions/checkout@v4
        with:
          repository: Ali-Moatazz/gold-
          token: ${{ needs.generate-token.outputs.app_token }}

      - name: Set Git user
        run: |
          git config user.name "Ali-Moatazz[bot]"
          git config user.email "Ali-Moatazz[bot]@users.noreply.github.com"

      - name: Create new branch and commit change
        run: |
          BRANCH="auto-pr-$(date +%s)"
          git checkout -b $BRANCH
          echo "Automated PR at $(date)" >> backup.txt
          git add backup.txt
          git commit -m "Automated PR test"
          git push origin $BRANCH
          echo "branch_name=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ needs.generate-token.outputs.app_token }}
          branch: ${{ env.branch_name }}
          title: "Automated PR from common-workflows"
          body: "This PR was created automatically using GitHub Actions."
          base: main

      - name: Merge Pull Request
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-merge@v3
        with:
          token: ${{ needs.generate-token.outputs.app_token }}
          repository: Ali-Moatazz/gold-
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
