name: Debug GitHub App Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    name: Generate GitHub App Token
    runs-on: ubuntu-latest
    outputs:
      app_token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: Debug secrets exist
        run: |
          echo "==== DEBUG: CHECKING APP_ID & APP_PEM ===="
          if [ -z "${{ secrets.APP_ID }}" ]; then
            echo "❌ APP_ID is empty!"
          else
            echo "✅ APP_ID length: $(echo -n "${{ secrets.APP_ID }}" | wc -c)"
            echo "APP_ID value: ${{ secrets.APP_ID }}"
          fi

          if [ -z "${{ secrets.APP_PEM }}" ]; then
            echo "❌ APP_PEM is empty!"
          else
            echo "✅ APP_PEM length: $(echo -n "${{ secrets.APP_PEM }}" | wc -c)"
            echo "First line of PEM: $(echo "${{ secrets.APP_PEM }}" | head -n 1)"
          fi
          echo "=========================================="

      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: "${{ secrets.APP_ID }}"
          private-key: "${{ secrets.APP_PEM }}"

      - name: Debug token from step
        run: |
          echo "==== DEBUG: APP TOKEN GENERATED ===="
          if [ -z "${{ steps.app-token.outputs.token }}" ]; then
            echo "❌ Token output is empty!"
          else
            echo "✅ Token length: $(echo -n "${{ steps.app-token.outputs.token }}" | wc -c)"
            echo "First 20 chars: $(echo -n "${{ steps.app-token.outputs.token }}" | cut -c1-20)"
          fi
          echo "===================================="

  checkout-to-gold:
    name: Checkout to gold repo
    runs-on: ubuntu-latest
    needs: generate-token
    steps:
      - name: Debug needs output
        run: |
          echo "==== DEBUG: NEEDS TOKEN ===="
          if [ -z "${{ needs.generate-token.outputs.app_token }}" ]; then
            echo "❌ TOKEN from needs is empty!"
          else
            echo "✅ TOKEN length: $(echo -n "${{ needs.generate-token.outputs.app_token }}" | wc -c)"
            echo "First 20 chars: $(echo -n "${{ needs.generate-token.outputs.app_token }}" | cut -c1-20)"
          fi
          echo "============================="

      - name: Checkout gold repo
        uses: actions/checkout@v4
        with:
          repository: Ali-Moatazz/gold
          token: ${{ needs.generate-token.outputs.app_token }}
