name: Test Workflow
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PEMCONTENTS }}

      - name: Checkout gold
        uses: actions/checkout@v4
        with:
          repository: Ali-Moatazz/gold
          token: ${{ steps.token.outputs.token }}
