name: Sync to Gold

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. Generate installation token from GitHub App
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PEMCONTENTS }}
          owner: Ali-Moatazz

      # 2. Checkout the gold repo with app token
      - name: Checkout gold repo
        uses: actions/checkout@v4
        with:
          repository: Ali-Moatazz/gold
          token: ${{ steps.app-token.outputs.token }}
          path: gold

      # 3. Make a change (example: update timestamp file)
      - name: Make change
        run: |
          cd gold
          echo "Updated at $(date)" > sync.txt

      # 4. Commit changes
      - name: Commit changes
        run: |
          cd gold
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b sync-update-branch
          git add .
          git commit -m "Automated sync update" || echo "No changes to commit"
          git push origin sync-update-branch || echo "No changes pushed"

      # 5. Create Pull Request
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          path: gold
          branch: sync-update-branch
          base: main
          title: "Automated Sync Update"
          body: "This PR was created automatically by GitHub Actions."

      # 6. Merge PR
      - name: Merge Pull Request
        if: steps.cpr.outputs.pull-request-number
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --admin --repo Ali-Moatazz/gold
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
