name: My Workflow

on:
  workflow_dispatch:

jobs:
  generate-token:
    name: Generate GitHub App token
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PEMCONTENTS }}

  checkout-to-gold:
    name: Checkout to gold repo
    runs-on: ubuntu-latest
    needs: generate-token
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          repository: Ali-Moatazz/gold
          token: ${{ needs.generate-token.outputs.app_token }}
          path: gold

  



  
