name: Debug Workflow

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Running generate-token job"
        id: hello
      - run: echo "fake-token-123" > token.txt
      - id: set-output
        run: echo "token=fake-token-123" >> $GITHUB_OUTPUT
    outputs:
      app_token: ${{ steps.set-output.outputs.token }}

  checkout-to-gold:
    needs: generate-token
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "==== DEBUG ===="
          echo "Token from needs: '${{ needs.generate-token.outputs.app_token }}'"
          echo "================"
