name: Sync to Gold Repo

on:
  workflow_dispatch:

jobs:
  sync-gold:
    name: Sync and PR to Gold Repo
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PEMCONTENTS }}

      

      - name: Checkout gold- repo
        uses: actions/checkout@v4
        # with:
        #   repository: Ali-Moatazz/gold
        #   token: ${{ steps.generate-token.outputs.token }}
        #   path: gold
          
      - name: Create hello.txt
        run: |
          touch hello.txt
          echo "Hello Ali" > hello.txt
          cat hello.txt
          ls

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b aly
          git add hello.txt
          git commit -m "Add hello.txt"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: aly
          # base: main
          title: "Add hello.txt"
          body: "This PR adds hello.txt with greeting message."

        
      - name: Push changes to new branch
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
            "timeout 30s git push --verbose origin aly"
  



      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
