name: Debug App Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    name: Generate GitHub App token
    runs-on: ubuntu-latest
    outputs:
      app_token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: Debug inputs
        run: |
          echo "APP_ID = ${{ secrets.APP_ID }}"
          echo "PEM length = $(echo "${{ secrets.PEMCONTENTS }}" | wc -c)"

      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PEMCONTENTS }}

      - name: Debug token length
        run: |
          echo "Generated token length = ${{ steps.app-token.outputs.token }}" | wc -c

  checkout-to-gold:
    needs: generate-token
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "==== DEBUG: NEEDS TOKEN ===="
          if [ -z "${{ needs.generate-token.outputs.app_token }}" ]; then
            echo "❌ TOKEN from needs is empty!"
          else
            echo "✅ TOKEN length: $(echo '${{ needs.generate-token.outputs.app_token }}' | wc -c)"
          fi
          echo "============================="

      - uses: actions/checkout@v4
        with:
          repository: Ali-Moatazz/gold
          path: gold
          token: ${{ needs.generate-token.outputs.app_token }}
